apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "plik.fullname" . }}
  labels:
    {{- include "plik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if eq .Values.kind "StatefulSet" }}
  serviceName: {{ include "plik.fullname" . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plik.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plik.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /home/plik/server/plikd.cfg
              subPath: plikd.cfg
            - name: data
              mountPath: {{ .Values.persistence.path }}
            - name: db
              mountPath: {{ .Values.dbPersistence.path }}
          envFrom:
            - secretRef:
                name: {{ include "plik.secretName" . }}
                optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "plik.fullname" . }}
        {{- if eq .Values.kind "Deployment" }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "plik.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: db
          {{- if .Values.dbPersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "plik.fullname" . }}-db
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
  {{- if eq .Values.kind "StatefulSet" }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    - metadata:
        name: db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.dbPersistence.storageClassName }}
        storageClassName: {{ .Values.dbPersistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.dbPersistence.size }}
  {{- end }}
