{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plik.fullname" . }}
  labels:
    {{- include "plik.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.googleApiSecret }}
  PLIKD_GOOGLE_API_SECRET: {{ .Values.secrets.googleApiSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.ovhApiSecret }}
  PLIKD_OVH_API_SECRET: {{ .Values.secrets.ovhApiSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.ovhApiKey }}
  PLIKD_OVH_API_KEY: {{ .Values.secrets.ovhApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcClientSecret }}
  PLIKD_OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.dataBackend }}
  PLIKD_DATA_BACKEND_CONFIG: {{ .Values.secrets.dataBackend | toJson | quote }}
  {{- end }}
  {{- if .Values.secrets.metadataBackend }}
  PLIKD_METADATA_BACKEND_CONFIG: {{ .Values.secrets.metadataBackend | toJson | quote }}
  {{- end }}
{{- end }}
